import { defineConfig, devices } from '@playwright/test';

// Generated by 'archetipo e2e ensure'. Video stays off globally; the demo
// recording is configured per-run by 'archetipo e2e demo'.
export default defineConfig({
  testDir: './e2e',
  // Rewrites docs/images, so it runs only from playwright.screenshots.config.ts
  testIgnore: 'screenshot.spec.ts',
  fullyParallel: true,
  reporter: 'list',
  use: {
    trace: 'on-first-retry',
    video: 'off',
  },
  projects: [
    { name: 'chromium', use: { ...devices['Desktop Chrome'] } },
  ],
});
