# Builds the settings in config.json (see config.example.json) into the firmware.
# ConfigManager::begin() applies them the first time a board boots the image.
Import("env")

import json
import os
import re
import sys

FIELDS = {
    "wifi": {"ssid": str, "password": str},
    "nut": {"username": str, "password": str, "ups_name": str},
    "mqtt": {"host": str, "port": int, "username": str, "password": str},
}
DEVICE_ID = re.compile(r"[A-Z0-9-]+-[0-9A-F]{6}")


def fail(message):
    print(f"config.json: {message}", file=sys.stderr)
    env.Exit(1)


def check(sections, where=""):
    for name, values in sections.items():
        if name not in FIELDS or not isinstance(values, dict):
            fail(f"{where}{name}: expected one of {', '.join(FIELDS)}")
        for field, value in values.items():
            kind = FIELDS[name].get(field)
            if kind is None:
                fail(f"{where}{name}.{field}: unknown setting")
            # type(), not isinstance(): true would pass as an int
            if type(value) is not kind:
                fail(f"{where}{name}.{field}: expected a {'number' if kind is int else 'string'}")
    wifi = sections.get("wifi", {})
    if not 1 <= len(wifi.get("ssid", "-").encode()) <= 32:
        fail(f"{where}wifi.ssid: expected 1 to 32 bytes")
    if len(wifi.get("password", "").encode()) > 64:
        fail(f"{where}wifi.password: expected at most 64 characters")
    if not 1 <= sections.get("mqtt", {}).get("port", 1883) <= 65535:
        fail(f"{where}mqtt.port: expected 1 to 65535")


path = os.path.join(env.subst("$PROJECT_DIR"), "config.json")
config = {}
# Test images leave the settings out: test_config_manager starts from an unconfigured board
if os.path.exists(path) and "test" not in env.GetBuildType():
    with open(path, encoding="utf-8") as f:
        try:
            config = json.load(f)
        except ValueError as e:
            fail(e)
    if not isinstance(config, dict):
        fail("expected an object")
    devices = config.pop("devices", {})
    if not isinstance(devices, dict):
        fail("devices: expected an object keyed by device ID")
    check(config)
    for device_id, sections in devices.items():
        if not DEVICE_ID.fullmatch(device_id.upper()) or not isinstance(sections, dict):
            fail(f"devices.{device_id}: expected settings under a device ID such as ESP32-S3-A1B2C3")
        check(sections, f"devices.{device_id}.")
    if devices:
        # Matched against getDeviceId(), which is upper case
        config["devices"] = {device_id.upper(): sections for device_id, sections in devices.items()}
    print("Building in the settings from config.json")

# A header rather than a -D flag: the shell would mangle quotes and '$' in passwords
out_dir = os.path.join(env.subst("$BUILD_DIR"), "generated")
os.makedirs(out_dir, exist_ok=True)
text = json.dumps(config, separators=(",", ":")) if config else ""
# "\?" keeps "??=" in a password from reading as a trigraph
literal = text.replace("\\", "\\\\").replace('"', '\\"').replace("?", "\\?")
with open(os.path.join(out_dir, "build_config_json.h"), "w", encoding="utf-8") as f:
    f.write("// Generated by scripts/build_config.py from config.json\n")
    f.write(f'static const char BUILD_CONFIG_JSON[] = "{literal}";\n')
env.Append(CPPPATH=[out_dir])
